server:
  port: 8080


spring:
  cloud:
    gateway:
      routes:
        - id: delivery-service
          uri: http://delivery-service:8080
          predicates:
            - Path=/delivery/**
          filters:
            - RewritePath=/delivery/(?<path>.*), /$\{path}

        - id: courier-service
          uri: http://courier-service:8080
          predicates:
            - Path=/courier/**
          filters:
            - RewritePath=/courier/(?<path>.*), /$\{path}

        - id: user-service
          uri: http://user-service:8080
          predicates:
            - Path=/user/**
          filters:
            - RewritePath=/user/(?<path>.*), /$\{path}

        - id: openapi
          uri: http://api-gateway:8080
          predicates:
            - Path=/v3/api-docs/**
          filters:
            - RewritePath=/v3/api-docs/(?<path>.*), /$\{path}/v3/api-docs

springdoc:
  version: '1.0.0'
  swagger-ui:
    use-root-path: true
    urls:
      - name: delivery
        url: /v3/api-docs/delivery
        display-name: Delivery Service
      - name: courier
        url: /v3/api-docs/courier
        display-name: Courier Service
      - name: user
        url: /v3/api-docs/user
        display-name: User Service